version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - ./dev.perfexia-consulting.fr:/home/wwwroot/dev.perfexia-consulting.fr
        depends_on:
          - php
        restart: always

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        restart: always

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - ./dev.perfexia-consulting.fr:/home/wwwroot/dev.perfexia-consulting.fr
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - mysql
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql
        restart: always

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - 8001:80
        restart: always
